name: Build and Push Docker Image

on:
  release:
    types:
      - published
      - edited

jobs:
  build-docker-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./Dockerfile
        continue-on-error: true

      - name: Dry run docker build process
        run: |
          docker build --progress=plain --no-cache -t test-image .
          
      - name: Security Scan with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'test-image'
          format: 'table'
          exit-code: 1
          severity: 'CRITICAL,HIGH'
  docker-build-and-push:
    needs: build-docker-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t aisuvro/fastapi-sample-project:${{ github.event.release.tag_name }} .

      - name: Push Docker Image to Docker Hub
        run: |
          docker push aisuvro/fastapi-sample-project:${{ github.event.release.tag_name }}
