name: Lint check and unit test

on:
  push:
    branches:
      - feature/**
  pull_request:
    branches:
      - feature/**

permissions:
  contents: read

jobs:
  link-check:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Build the docker
        run: docker compose build

      - name: Install Dependencies
        run: |
          pip install --no-cache-dir -r app/requirements.txt
          pip install pytest

      - name: Run Tests
        run: |
          pytest app/tests/
