name: PR to Development branch

on:
    workflow_run: 
        workflows: ["Docker Build Check"]
        types:
            - completed

permissions:
  contents: read
  pull-requests: write

jobs:
  pr-to-dev:
    runs-on: ubuntu-latest

    steps:
          - name: Checkout repository
            uses: actions/checkout@v4
    
          - name: Create Pull Request
            env:
              GH_TOKEN: ${{ secrets.GIT_TOKEN }}
            run: |
              if gh pr list --base development --head feature/api-v1 --state open | grep -q "feature/api-v1"; then
                echo "PR already exists, skipping creation."
              else
                gh pr create \
                  --base development \
                  --head feature/api-v1 \
                  --title "Auto PR: Merge feature/api-v1 into development" \
                  --body "This pull request was automatically created by GitHub Actions."
                echo "PR created successfully."
              fi
